FROM node:16-alpine3.14

LABEL maintainer="lance.donnell@datacom.co.nz"

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

# default to port 19006 for node, and 19001 and 19002 (tests) for debug
ARG PORT=19006
ENV PORT $PORT
EXPOSE $PORT 19001 19002

# install global packages
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH /home/node/.npm-global/bin:$PATH
# RUN npm i --unsafe-perm -g chokidar
RUN npm i --unsafe-perm -g npm@latest expo-cli@latest

WORKDIR /app
# ENTRYPOINT ["npm", "run"]
# ENTRYPOINT ["expo", "start"]
# CMD ["web"]