version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    depends_on: [db]
    volumes:
      - ./api:/app
    ports:
      - 8080:80
    networks:
      - recipe-share-network
    env_file:
      - .env

  db:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - recipe-share-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
      args:
        - NODE_ENV=development
    volumes:
      - ./frontend:/app
    ports:
      - 19001:19001
      - 19002:19002
      - 19006:19006
    networks:
      - recipe-share-network
    env_file:
      - .env
    tty: true
    command: expo web

  testdb:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - recipe-share-network

networks:
  recipe-share-network:
